
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthWrapper } from './countexts/auth'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthWrapper>
        <body className='bg-white'>
          <main className='font-sans'>
            {children}
          </main>
        </body>
      </AuthWrapper>
    </html>
  )
}
